### ISSUE TITLE
Question about 'visual information'

### ISSUE THREAD

**Issue by YoruCathy** [cognitiveailab/alfred-gpt2#1]
Hello Peter, thanks for your interesting work!
Some questions about visual information mentioned in the paper:
`When a
small amount of visual information is incorporated, namely the starting location in the virtual environment`
I am confused what the 'starting location' means and how you encode this in your code.
Best,
Ruolin

**Comment by PeterAJansen** [comment]
Dear Roulin,

Thanks for your question and interest in this work.  I think your question is about this section:

"In analyzing the visual semantic plans,the first command is typically to move the virtualagent to a starting location that contains the firstobject it must interact with (for example, movingto the countertop, where a potato is resting in theinitialized virtual environment, to begin a directive about slicing, washing, and heating a potatoslice). If we supply the model with this single pieceof visual information from the environment, full sequence prediction accuracy for all models morethan doubles, increasing to 53% in the strict condition, and 58% with permissive scoring, for thebest-performing GPT-2 model."

The issue is that nearly all the visual semantic plans start with a "GOTO <location>" command, e.g. "GOTO countertop", and that's one piece of information that's very hard to capture with the approach this paper is about (generating the visual semantic plans without any visual/environmental input).  For the evaluation here -- simulating giving the model that first "GOTO <location>" command, the performance (e.g. percent correct) of the visual semantic plans is just evaluated from the second command onward, assuming that the first command is supplied to the model.  Because it's a GPT-2 model, there is no resnet or other visual information used -- the entire model just uses the command sequence triples from the json files.  When you do this, the performance almost doubles (and increases over 50%), suggesting that the agent has learned the majority of the general sequence of the tasks, and just needs to be placed in the start position to do them correctly. 

If you have any questions, please let me know. 
best wishes,
Peter

**Comment by YoruCathy** [comment]
Got it, thanks for reply!
